runtime: nodejs16

automatic_scaling:
  target_cpu_utilization: 0.8
  min_instances: 1
  max_instances: 1
  min_pending_latency: 30ms
  max_pending_latency: automatic

network:
  session_affinity: true
